[package]
name = "trajectory-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
tonic = "0.10"
rust_decimal = "1.34"
thiserror = "2.0.12"
num-format = "0.4"
num = "0.4"

[build-dependencies]
tonic-build = "0.10"
